language: csharp
mono: none
dotnet: 2.0.3
sudo: false
cache:
  directories:
  - "$HOME/.nuget/"
before_install:
- set -e
script:
- "./$CODEBASE/scripts/build"
notifications:
  slack:
    rooms:
    - secure: sGFby414VD00jEUS58/luN+DOklSeRd2yv1N56KdKxK8VKbfYyAgLoXDxPGVJJCcS7dNRw9I/JRfh77eWL1Hy8zHHxu+FnPASbFL9GeNmD705EPiczDMITRNtVK9DO+KnBJlVj2+0CRaaGL7onk7PMdJB9w7gqGZlBIJfBTbg3e7yjkUEub+F6KbiF3Yp9730mdn/2Hn+NM/18p3Tm998lCkk1rFN2nV4oi4dEP6e30RAZDz8X0Iwvvw/qxCyT2aHt4l8WljX5IuD4A0xVz+0pzJswkeclNVkRIUfxRGvZOhiuyDcLCmVb7sXhgdc3A6xNoMyk0pbhgpxP62PZOGrxm3E8tYhB44/AWq4gxWTC1S9GVeDNZMwU+02xk/W6dbRaTo0romrWmaEngZNMthLnhzWdM1+x9IU9YUhvjRMLQUoSCg4lNSfA4vabOLrB3XIXi1ihaf2nQBH90UYvLG7UL+IgJe5WSyVObdjuYLBH4xtTXiI+XR2pFUHpybROAYp9SMfWmFkmuH7J05iFXrQ7nhEOy62pHOgDXpAeyiOG4cn2X8qfwQwrxrXvPTnjNQsYpZHfPE2GBY4aWuW0dYsXyl42Tr60uhe6PNGYT/qwrnSxUiJSBQLXXJ6XzQClIQlI5IiQD2RXuuR8ZaefQlOLsLRqvpePG2uysF/ZNHXfs=
