#!/usr/bin/env bash

# Note: use lowercase names for the Docker images
DOCKER_IMAGE="azureiotpcs/remote-monitoring-nginx:latest"
PORT=10080

set -e

echo Using port $PORT...
docker run -it -p $PORT:10080 $DOCKER_IMAGE

set +e
