#!/usr/bin/env bash -e

# Note: use lowercase names for the Docker images
DOCKER_IMAGE="rb531/azure-mesh-amt"

APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

run_container() {
    check_dependency_docker

    $APP_HOME/scripts/env-vars-check

	echo "Starting Mesh AMT Server ..."
	docker run -it -p 9010:9010 \
        -e PCS_IOTHUB_CONNSTRING \
        -e PCS_CONFIG_WEBSERVICE_URL \
        -e PCS_AUTH_ISSUER \
        -e PCS_AUTH_AUDIENCE \
        "$DOCKER_IMAGE:testing"
}

run_container
